# Generated by Django 4.2 on 2026-08-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate_type',
            field=models.CharField(choices=[('white_black', 'White Plate / Black Text — Private (Non-Commercial)'), ('yellow_black', 'Yellow Plate / Black Text — Commercial'), ('green_white', 'Green Plate / White Text — EV Private'), ('green_yellow', 'Green Plate / Yellow Text — EV Commercial'), ('black_yellow', 'Black Plate / Yellow Text — Self-Drive Rental'), ('red_white', 'Red Plate / White Text — Temporary Registration'), ('blue_white', 'Blue Plate / White Text — Diplomatic'), ('red_emblem', 'Red Plate / National Emblem — President / Governor'), ('arrow_red', 'Arrow (↑) / Red — Military / Defence'), ('bh_series', 'BH Series / Black — Transferable (Pan-India)')], default='white_black', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='state_code',
            field=models.CharField(blank=True, help_text='e.g. MH, DL, KA', max_length=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(help_text='e.g. MH 12 AB 1234 or BH 24 ZA 0001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Auto', 'Auto'), ('Truck', 'Truck'), ('Bus', 'Bus'), ('EV', 'Electric Vehicle'), ('Military', 'Military / Defence'), ('Diplomatic', 'Diplomatic')], max_length=20),
        ),
    ]
